web:
    container_name: proxy
    image: jwilder/nginx-proxy
    restart: always
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - /var/run/docker.sock:/tmp/docker.sock
        - ./src/nginx.tmpl:/app/nginx.tmpl
        - ./certs:/etc/nginx/certs
