mysql-server:
    ports:
      - "3306:3306"
    container_name: mysql57
    image: mysql:5.7
    volumes:
      - ./src/run.sh:/code/run.sh
      - "./.data/db:/var/lib/mysql"
    #command: "chmod 777 /code/run.sh"
    #command: "/code/run.sh"
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: 123456 
        MYSQL_DATABASE: "dockerdb"
        MYSQL_USER: myqsl 
        MYSQL_PASSWORD: 123456 
